version: '3.4'

services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5340:80

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssword
    ports:
      - 5341:3306
      
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=P@ssword
    ports:
      - 5343:27017

  api:
    build:
      context: .
      dockerfile: DoorUnlocker.API/Dockerfile
    environment:
      - ConnectionStrings__DbConnection=server=mysql;port=3306;database=door-unlocker;uid=root;password=P@ssword
      - SeqServer=http://seq
      - MongoConnection__ConnectionString=mongodb://root:P%40ssword@mongo
      - IdentityServer__Authority=http://ids
    ports:
      - 5344:80
    depends_on:
      - mysql
      - mongo
      - seq

  ids:
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    environment:
      - SeqServer=http://seq
    ports:
      - 5345:80
    depends_on:
      - seq

